import os
from pathlib import Path

def update_icons():
    """Scans assets/icons/ and generates icons.py with SVG_ICONS dictionary."""
    base_dir = Path(__file__).parent
    icons_dir = base_dir / "assets" / "icons"
    output_file = base_dir / "icons.py"

    if not icons_dir.exists():
        print(f"Error: {icons_dir} not found!")
        return

    print(f"Scanning {icons_dir}...")
    svg_icons = {}

    for svg_file in icons_dir.glob("*.svg"):
        name = svg_file.stem
        with open(svg_file, "r", encoding="utf-8") as f:
            content = f.read()
            # Replace currentColor or specific colors with {color} placeholder for UI styling
            # This allows ui.py to inject dynamic colors
            content = content.replace('stroke="currentColor"', 'stroke="{color}"')
            content = content.replace('fill="currentColor"', 'fill="{color}"')
            
            # Remove XML declaration and comments if any
            if "<?xml" in content:
                content = content[content.find("?>")+2:].strip()
            
            svg_icons[name] = content
            print(f"  + Added: {name}")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# Generated by update_icons.py\n\n")
        f.write("SVG_ICONS = {\n")
        for name, content in svg_icons.items():
            # Use triple quotes for multiline strings and escape { and } if needed
            # But the ui.py expects '{color}' so we should keep it.
            # We use repr() to handle escaping properly
            f.write(f"    '{name}': {repr(content)},\n")
        f.write("}\n")

    print(f"Successfully generated {output_file} with {len(svg_icons)} icons.")

if __name__ == "__main__":
    update_icons()
